# Generated by Django 5.0.6 on 2024-06-21 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptanceFeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(decimal_places=2, default=30000, max_digits=6)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BirthCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='birth_certificates/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuarantorLetterOfUndertaking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('CLERGY', 'Clergy'), ('CLERIC', 'Cleric'), ('PUBLIC_SERVANT', 'Public Servant')], max_length=50)),
                ('file', models.FileField(upload_to='letters_of_undertaking/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JAMBAdmissionLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='jamb_admission_letters/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JAMBResultSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='jamb_results/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocalGovernmentCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='local_gov_certifications/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalExaminationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='medical_forms/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OLevelResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('WAEC', 'WAEC'), ('NECO', 'NECO')], max_length=50)),
                ('file', models.FileField(upload_to='o_level_results/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParentLetterOfUndertaking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('PARENT', 'Parent'), ('GUARDIAN', 'Guardian')], max_length=50)),
                ('file', models.FileField(upload_to='letters_of_undertaking/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolAdmissionLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='school_admission_letters/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentBioData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='student_bio_data/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('JAMB_ADMISSION_LETTER_RE_UPLOAD', 'Re-upload JAMB Admission Letter'), ('SCHOOL_ADMISSION_LETTER_RE_UPLOAD', 'Re-upload School Admission Letter'), ('JAMB_RESULT_SLIP_RE_UPLOAD', 'Re-upload JAMB Result Slip'), ('O_LEVEL_RESULT_RE_UPLOAD', "Re-upload O'Level Result"), ('MEDICAL_EXAMINATION_FORM_RE_UPLOAD', 'Re-upload Medical Examination Form'), ('PARENT_LETTER_OF_UNDERTAKING_RE_UPLOAD', 'Re-upload Parent Letter Of Undertaking'), ('GUARANTOR_LETTER_OF_UNDERTAKING_RE_UPLOAD', 'Re-upload Guarantor Letter Of Undertaking'), ('BIRTH_CERTIFICATE_RE_UPLOAD', 'Re-upload Birth Certificate'), ('LOCAL_GOVERNMENT_CERTIFICATE_RE_UPLOAD', 'Re-upload Local Government Certification'), ('BIO_DATA_RE_UPLOAD', 'Re-upload Bio-data'), ('ALL_DOCUMENTS_RE_UPLOAD', 'Re-upload All Documents'), ('COMPLETED', 'Completed')], default='PENDING_PAYMENT', max_length=100)),
                ('acceptance_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MySite.acceptancefeepayment')),
                ('bio_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MySite.studentbiodata')),
                ('birth_certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MySite.birthcertificate')),
                ('jamb_admission_letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MySite.jambadmissionletter')),
                ('jamb_result_slip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MySite.jambresultslip')),
                ('letter_of_undertaking_guarantor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guarantor_undertaking', to='MySite.guarantorletterofundertaking')),
                ('letter_of_undertaking_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_undertaking', to='MySite.parentletterofundertaking')),
                ('local_government_certification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MySite.localgovernmentcertification')),
                ('medical_examination_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MySite.medicalexaminationform')),
                ('o_level_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MySite.olevelresult')),
                ('school_admission_letter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MySite.schooladmissionletter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
