# Generated by Django 5.0.6 on 2024-06-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptancefeepayment',
            name='fee',
            field=models.IntegerField(default=30000),
        ),
    ]
