# Generated by Django 5.0.6 on 2024-06-24 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0002_alter_acceptancefeepayment_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='acceptance_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MySite.acceptancefeepayment'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='jamb_admission_letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MySite.jambadmissionletter'),
        ),
    ]
