# Generated by Django 5.0.6 on 2024-06-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0004_alter_studentregistration_registration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='registration_status',
            field=models.CharField(choices=[('Pending Payment', 'Pending Payment'), ('Upload All Documents', 'Upload All Documents'), ('Re-upload JAMB Admission Letter', 'Re-upload JAMB Admission Letter'), ('Re-upload School Admission Letter', 'Re-upload School Admission Letter'), ('Re-upload JAMB Result Slip', 'Re-upload JAMB Result Slip'), ("Re-upload O'Level Result", "Re-upload O'Level Result"), ('Re-upload Medical Examination Form', 'Re-upload Medical Examination Form'), ('Re-upload Parent Letter Of Undertaking', 'Re-upload Parent Letter Of Undertaking'), ('Re-upload Guarantor Letter Of Undertaking', 'Re-upload Guarantor Letter Of Undertaking'), ('Re-upload Birth Certificate', 'Re-upload Birth Certificate'), ('Re-upload Local Government Certification', 'Re-upload Local Government Certification'), ('Re-upload Bio-data', 'Re-upload Bio-data'), ('Re-upload All Documents', 'Re-upload All Documents'), ('Completed', 'Completed')], default='Pending Payment', max_length=100),
        ),
    ]
